### ISSUE TITLE
Cannot get player specific slots in close handler.

### ISSUE THREAD

**Issue by TheDeafCreeper** [IPVP-MC/canvas#28]
It seems like that a player is removed from the menu before the close handler is triggered:
```
MenuHolder holder = (MenuHolder) currentInventory;
holders.remove(holder);
if (triggerCloseHandler) {
    getCloseHandler().ifPresent(h -> h.close(viewer, this));
}
```
which prevents you from using things like `Slot::getItem(player)` inside of close handlers.
Would just swapping around the close handler and removing the holder work and fix this?

**Comment by sainttx** [comment]
Hey @TheDeafCreeper, I'm not sure I understand why you can't use `Slot#getItem(Player` inside of the close handler. The close handler is called with reference of which player closed the menu, so you should be able to do something like the following:
```java
menu.setCloseHandler((closingPlayer, closedMenu) -> {
    Slot slot = closedMenu.getSlot(0);
    ItemStack item = slot.getItem(closingPlayer);
    /* do something with rendered item */
});
```

**Comment by TheDeafCreeper** [comment]
I just realized I put getItem not getRawItem (idk if it matters in this case), but currently when attempting to get the item for a specific player I get this error in the console:
```
[14:08:10 ERROR]: Could not pass event InventoryCloseEvent to SantoriaFoxcore v1.4.1
java.lang.IllegalStateException: Player not viewing parent menu
        at org.ipvp.canvas.slot.DefaultSlot.getRawItem(DefaultSlot.java:118) ~[SantoriaFoxcore-1.4.1.jar:?]
        at com.jjkay03.santoriafoxcore.fishing.fisherman.Fisherman.createMenu$lambda$4(Fisherman.kt:60) ~[SantoriaFoxcore-1.4.1.jar:?]
        at org.ipvp.canvas.type.AbstractMenu.lambda$closedByPlayer$0(AbstractMenu.java:203) ~[SantoriaFoxcore-1.4.1.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at org.ipvp.canvas.type.AbstractMenu.closedByPlayer(AbstractMenu.java:203) ~[SantoriaFoxcore-1.4.1.jar:?]
        at org.ipvp.canvas.MenuFunctionListener.triggerCloseHandler(MenuFunctionListener.java:292) ~[SantoriaFoxcore-1.4.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor12.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-365]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-365]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-365]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1678) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2875) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2868) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-365]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```


Changing the code to
```java
MenuHolder holder = (MenuHolder) currentInventory;
holders.remove(holder);
if (triggerCloseHandler) {
    getCloseHandler().ifPresent(h -> h.close(viewer, this));
}
```

as I mentioned in the issue fixes that error.

**Comment by sainttx** [comment]
Hm, will need to test this out. The validation on `getRawItem` calls `AbstractMenu#isOpen` which implements:
```java
@Override
public boolean isOpen(Player viewer) {
    Bukkit.getLogger().info("Checking if menu " + this + " is open for player " + viewer.getName());
    InventoryHolder currentInventory =
            viewer.getOpenInventory().getTopInventory().getHolder();
    return currentInventory instanceof MenuHolder && ((MenuHolder) currentInventory).getMenu() == this;
}
```
In theory the `holders.remove(holder)` call shouldn't change the outcome of `isOpen` (since it's based on the currently open inventory) in the same call-chain so I'm curious why it's passing in `closedByPlayer` and then failing in the close handler.

**Comment by sainttx** [comment]
Disregard the above, I had a modified local branch on and the code was slightly different. Will play around with this as in the past there have been issues with opening menus also due to the order of `holders.remove`.

**Comment by sainttx** [comment]
@TheDeafCreeper give the latest commit a try - should resolve the issue
